### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by MacXatu** [grover/homebridge-dacp#1]
Great job and great idea to simulate a remote control to enable this on homebridge.

I would like to get a better understanding for how features work. Do we have to configure them? How are they written in the config.json? 

Please provide an example.

**Comment by grover** [comment]
The block for an Apple TV would be:

```
        {
          "name": "Apple TV",
          "pairing": "...",
          "serviceName": "...",
          "features": {
            "volume-control": false
          }
```

Volume controls is the only feature that can be left out right now. Added this to the README.md too.

Thanks!

**Comment by grover** [comment]
I just pushed a new version with an updated README.md with more explanations. I hope this helps.

**Comment by MacXatu** [comment]
Let me take a look. 

My first difficulty was understanding that the entire thing. 

Maybe start the first paragraph by saying “This plugin takes advantage of the ability to create your own remotes to control iTunes and Apple TV via Elgato app”. 

Thanks in advance
