### ISSUE TITLE
Doesn't load paring code and service name.

### ISSUE THREAD

**Issue by aaronjamt** [grover/homebridge-dacp#11]
I have installed this plugin, but when I paired my Apple TV and added the codes to the config like so:
`{
	"platform": "DACP",
	"devices": [
		{
			"name": "Apple TV",
			"paring": "PARING-CODE-HERE",
			"serviceName": "SERVICE-NAME-HERE"
		}
	]
}`, the console still says: 

> [2018-1-5 14:44:02] [DACP] Initializing DACP platform...
>[2018-1-5 14:44:02] [DACP] DACP Platform Plugin Loaded
>[2018-1-5 14:44:02] [DACP] Found accessory in config: "Apple TV"
>[2018-1-5 14:44:02] [DACP]
>[2018-1-5 14:44:02] [DACP] Skipping creation of the accessory "Apple TV" because it doesn't have a pairing code or
>[2018-1-5 14:44:02] [DACP] service name yet. You need to pair the device/iTunes, reconfigure and restart homebridge.
>[2018-1-5 14:44:02] [DACP]
>[2018-1-5 14:44:02] [DACP] Beginning remote control announcements for the accessory "Apple TV".
>[2018-1-5 14:44:02] [DACP]
>[2018-1-5 14:44:02] [DACP]      Use passcode 1501 to pair with this remote control.
>[2018-1-5 14:44:02] [DACP]

Why isn't it working/what have I done wrong?

**Comment by grover** [comment]
You misspelled pairing in the JSON configuration: You wrote "paring" instead of "pa**i**ring".

**Comment by aaronjamt** [comment]
Thanks, @grover . That was my issue.
