### ISSUE TITLE
Unable to get plugin working

### ISSUE THREAD

**Issue by usmcguy** [grover/homebridge-dacp#13]
I was able to get the plugin to appear as a Bridge in the Home app. I had to use the "alternate-playpause-switch": true value to get the AppleTV to play/pause. However, it only worked once in the Home App. After that, no play or pause.  Same goes for the Eve app.  I could only play/pause once. Never received any values for the metadata fields. Skip didnt work either.

**Comment by grover** [comment]
Unfortunately my crystal ball is broken... Could you provide me a homebridge log to take a look?
