### ISSUE TITLE
Provide an example folder with different config.json examples

### ISSUE THREAD

**Issue by grover** [grover/homebridge-dacp#14]
Provide example homebridge configurations for the various uses of this plugin.

**Comment by Solusan** [comment]
Hi @grover 

Yes. It would be great if you can provide an example folder with different config.json cause I'd like to implement more than only the play/pause feature like, "Now Playing" for example.

Thanks alot.

**Comment by grover** [comment]
Available now in [examples](https://github.com/grover/homebridge-dacp/tree/master/examples) along with updated documentation.
