### ISSUE TITLE
Command Details

### ISSUE THREAD

**Issue by jasonpaulso** [grover/homebridge-dacp#15]
I've got this plugin working insofar as I can use the alternate-playpause-switch feature to play/pause (on/off) my Apple TV via the Home App. What I am unclear on is if there is any other functionality available to me and if so-how do I utilize it.

**Comment by grover** [comment]
Unfortunately with Apples restrictive handling of HomeKit characteristics that's the only one you have available ATM. Other functionality is available only if you use less restrictive apps, such as Elgatos Eve app to at least set up your rules.

Features available if you use one of the other apps:
- Track skipping
- Now playing information
- And upcoming: Playlist controls

**Comment by jasonpaulso** [comment]
That is what I thought you’d say. Such a missed opportunity if you ask me. Thanks for your work nevertheless!

**Comment by grover** [comment]
There’s little I can do about this :(. Keep an eye on this. Maybe I’ll be able to pull some tricks, but don’t bet on it.
