### ISSUE TITLE
how to control volume?

### ISSUE THREAD

**Issue by toshibochan** [grover/homebridge-dacp#16]
i change the "no-volume-control" to false but i dont see any change on in the home app to change volume.
please help

thanks

**Comment by toshibochan** [comment]
my is apple tv 4 and 4k
on the EVE app i can see the volume but not controlling my receiver. skip not working to.

**Comment by grover** [comment]
Two things: Volume controls are not supported in the Home app.

The other one: Apple TV does not control the volume in the classical sense - your AVR does. As such this setting is iTunes only. As I wrote in the documentation:

> If true, disables the mute and volume control characteristic provided by the Speaker service. This is most useful for Apple TV, which performs volume control through external devices like a TV or A/V receiver.
