### ISSUE TITLE
How to use the TV/Home button

### ISSUE THREAD

**Issue by oscarc23** [grover/homebridge-dacp#18]
Hi, is there any way to use the TV/Home button with this plugin? With the Play/Pause button it sometimes do not turn on my TV depending if the Apple TV was already on or just playing music through the AVR with the TV off, instead the TV/Home button always send the HDMI signal to turn on the TV and change the input.

**Comment by grover** [comment]
Strange. My AppleTV always insists on taking control if I play/pause.

Unfortunately I don’t know if its possible to simulate the TV Button.

**Comment by stephenwoodford** [comment]
https://github.com/postlund/pyatv/blob/master/docs/protocol.rst#controlpromptentry

Looks like menu, topmenu, and select are available through DAAP.

**Comment by grover** [comment]
I plan to add this feature in 0.9.0. Stay tuned.

**Comment by grover** [comment]
Done in https://github.com/grover/homebridge-dacp/releases/tag/v0.9.0

**Comment by stephenwoodford** [comment]
I’m not able to get this working with 0.9. Both the regular and alternate options don’t show any of the input options in Eve or Home apps. I tried unpairing and re-pairing, removing all other features, etc. Anything else I should try?

**Comment by kapps7** [comment]
Is the new topmenubutton another name for the Home button ?

**Comment by grover** [comment]
@stephenwoodford could you please open a new issue with your config for it? I’ll help you get it running.

@kapps7 topmenu is the official name of the TV button on the top right of the Apple TV 4 and later remote controls.
