### ISSUE TITLE
Play pause on Apple TV via Home not working

### ISSUE THREAD

**Issue by hessius** [grover/homebridge-dacp#19]
I can't get this to work, I've managed to connect the remote to my Apple TV, everything looks fine in the logs but nothing is happening on my tv. I've enabled alternate-playpause-switch:

```

"devices": [
                {
                    "name": "New Remote Control",
                    "pairing": "xxxx",
                    "serviceName": "xxxx",
                    "features": {
                        "no-volume-controls": true,
                        "alternate-playpause-switch": true
                    }
                }
            ]
```

> Feb 09 12:42:53 pihole homebridge[3603]: [2018-2-9 12:42:53] [DACP] Setting current playback state: paused
> Feb 09 12:42:53 pihole homebridge[3603]: [2018-2-9 12:42:53] [DACP] Playback status update done.

My ATV is on the 10.3 beta, might that be the issue?

**Comment by grover** [comment]
Seems like tvOS 11.3 is breaking stuff - see https://github.com/grover/homebridge-dacp/issues/17
