### ISSUE TITLE
Home on iPhone 6S

### ISSUE THREAD

**Issue by MacXatu** [grover/homebridge-dacp#2]
Home on iPhone 6S shows both iTunes and Apple TV as unsupported accessories.

Everything looks fine in the log:
[2017-12-10 00:05:46] [DACP] Session ID 1161782168
[2017-12-10 00:05:46] [DACP] Connected to Macintosh’s Library
[2017-12-10 00:05:46] [DACP] Session ID 7
[2017-12-10 00:05:46] [DACP] Updating characteristics with current volume: v=100
[2017-12-10 00:05:46] [DACP] Connected to Apple TV (4)

Only errors on log are the well known Apple Bonjour warning:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.

And "sys is deprecated":
(node:12731) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.

**Comment by grover** [comment]
Sadly Home will not deal with custom characteristics or services that haven't been defined by Apple. There's no Apple defined services for media playback control. I expect that to change somewhat with the HomePod.

As such the only service that should be available is the Speaker controls - those should be visible and useable in Home.

An app were all of this works is [Elgato Eve](https://itunes.apple.com/de/app/elgato-eve/id917695792?mt=8).

Sorry, but this nothing I can change.
