### ISSUE TITLE
PR Proposal

### ISSUE THREAD

**Issue by JamesMensah** [grover/homebridge-dacp#22]
Hi, I'd like to submit a new branch and PR to add a sleep mode to turn the appletv off
I'm a bit new to GitHub and wondering how do i push my branch to your project?
I don't seem to have permission

remote: Permission to grover/homebridge-dacp.git denied to JamesMensah.
fatal: unable to access 'https://github.com/grover/homebridge-dacp.git/': The requested URL returned error: 403

Thanks,
James

**Comment by grover** [comment]
Hey James!

You fork the project, then you push in your fork and finally submit a pull request form there.

Sounds like a cool submission - I've been asked if one could restart the AppleTV this way - do you know something about that?

Michael

**Comment by JamesMensah** [comment]
Thanks! I will do that.

Well i guess you could do a restart yes if you're able to put it in sleep mode and then wake it up again.
