### ISSUE TITLE
Playlist switch?

### ISSUE THREAD

**Issue by dguazzon** [grover/homebridge-dacp#30]
I can play pause the current selected playlist in iTunes but I don't see the playlists in Home, thus I'm not able to switch between them.

How should the config looks like to let the playlist show up as a switch?

**Comment by grover** [comment]
Does https://github.com/grover/homebridge-dacp/blob/master/docs/configuration/playlists.md answer your question?

**Comment by dguazzon** [comment]
Actually not really.
Here is my actual config:

{
  "bridge": {
    "name": "HB-iTunes",
    "username": "A1:23:B3:56:78:CD",
    "port": 51827,
    "pin": "031-45-156",
    "manufacturer": "@nfarina",
    "model": "homebridge",
    "serialNumber": "0.4.20"
  },
  "accessories": [],
  "platforms": [
    {
      "platform": "DACP",
      "devices": [
        {
          "name": "iTunes",
          "pairing": "E1855E19F1062833",
          "serviceName": "5D23C6C4F8A59F24",
          "features": {
            "album-artwork": "/tmp/nowplaying.png",
            "alternate-playpause-switch": true
          },
          "playlists": [
            "Energy",
            "Radio24"
          ]
        }
      ]
    }
  ]
}

It works fine, in the sense that I can start playing the last chosen playlist. In Apple Home I simply get an "iTunes" switch but nothing else.

**Comment by grover** [comment]
The playlist feature is not supported in the Apple Home app.
