### ISSUE TITLE
Long press on TopMenu button in Macros?

### ISSUE THREAD

**Issue by StewartSnow** [grover/homebridge-dacp#32]
Hey, would it be possible to get the macro part of the plugin to be able to initiate a long-press of the TopMenu button?

Reason being being able to create a macro that can put an AppleTV to sleep - i.e. long press (brings up the sleep menu), normal press of Select, and the Apple TV sleeps.

**Comment by grover** [comment]
Unfortunately that's not possible via DACP. I'm thinking of supporting the media remote protocol for v2, which would also enable this function.

**Comment by shandorka** [comment]
Also need longpress to simulate switch off an Apple TV.

Or maybe you have universal macros to do this?

**Comment by grover** [comment]
As I wrote above it's impossible to send a long press using the protocols used by this plugin. Sorry.
