### ISSUE TITLE
no buttons in home app

### ISSUE THREAD

**Issue by terencefaul** [grover/homebridge-dacp#33]
I have everything setup but get no buttons in home app.

this is in log, not sure if related

Skipping 'mdbk' - don't know how to parse. length=4
Skipping 'aeCs' - don't know how to parse. length=4
Skipping 'aeIM' - don't know how to parse. length=8
Skipping 'meds' - don't know how to parse. length=4
Skipping 'mdbk' - don't know how to parse. length=4
Skipping 'aeCs' - don't know how to parse. length=4
Skipping 'meds' - don't know how to parse. length=4
Skipping 'mdbk' - don't know how to parse. length=4
Skipping 'aeHS' - don't know how to parse. length=1
Skipping 'aeCs' - don't know how to parse. length=4
Skipping 'mrpr' - don't know how to parse. length=8
Skipping 'aeRM' - don't know how to parse. length=8
Skipping 'meds' - don't know how to parse. length=4
Skipping 'mdbk' - don't know how to parse. length=4
Skipping 'aeHS' - don't know how to parse. length=1
Skipping 'aeCs' - don't know how to parse. length=4
Skipping 'mrpr' - don't know how to parse. length=8
Skipping 'aeRM' - don't know how to parse. length=8
Skipping 'meds' - don't know how to parse. length=4
Skipping 'mdbk' - don't know how to parse. length=4
Skipping 'aeHS' - don't know how to parse. length=1
Skipping 'aeCs' - don't know how to parse. length=4
Skipping 'mrpr' - don't know how to parse. length=8
Skipping 'aeRM' - don't know how to parse. length=8
Skipping 'meds' - don't know how to parse. length=4

**Comment by grover** [comment]
No, that's unrelated. Have you read the features documentation? Have you read of the Home.app specific features and enabled them in your configuration?

**Comment by terencefaul** [comment]
I have read everything and tried it in the home app and Hesperus.
