### ISSUE TITLE
Fehler bei erstinstallation

### ISSUE THREAD

**Issue by fettesb** [grover/homebridge-dacp#39]
> Apr 03 14:48:21 hbridge2 homebridge[1463]: [2018-4-3 14:48:21] [DACP] Starting DACP browser...
Apr 03 14:48:21 hbridge2 homebridge[1463]: /usr/local/lib/node_modules/homebridge-dacp/src/index.js:79
Apr 03 14:48:21 hbridge2 homebridge[1463]:       const artwork = device.features['album-artwork'];
Apr 03 14:48:21 hbridge2 homebridge[1463]:                                      ^
Apr 03 14:48:21 hbridge2 homebridge[1463]: TypeError: Cannot read property 'album-artwork' of undefined
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at config.devices.forEach.device (/usr/local/lib/node_modules/homebridge-dacp/src/index.js:79:38)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at Array.forEach (<anonymous>)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at DacpPlatform._enableArtworkCameras (/usr/local/lib/node_modules/homebridge-dacp/src/index.js:78:25)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at DacpPlatform._didFinishLaunching (/usr/local/lib/node_modules/homebridge-dacp/src/index.js:72:10)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at API.emit (events.js:185:15)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:98:13)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at Module._compile (module.js:649:30)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at Object.Module._extensions..js (module.js:660:10)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at Module.load (module.js:561:32)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at tryModuleLoad (module.js:501:12)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at Function.Module._load (module.js:493:3)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at Function.Module.runMain (module.js:690:10)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at startup (bootstrap_node.js:194:16)
Apr 03 14:48:21 hbridge2 homebridge[1463]:     at bootstrap_node.js:666:3
Apr 03 14:48:21 hbridge2 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 14:48:21 hbridge2 systemd[1]: homebridge.service: Unit entered failed state.
Apr 03 14:48:21 hbridge2 systemd[1]: homebridge.service: Failed with result 'exit-code'.
Apr 03 14:48:31 hbridge2 systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Apr 03 14:48:31 hbridge2 systemd[1]: Stopped Node.js HomeKit Server.
Apr 03 14:48:31 hbridge2 systemd[1]: Started Node.js HomeKit Server.

**Comment by grover** [comment]
This issue should be fixed with 0.9.2. If it doesn't work for you, please reopen this issue.
