### ISSUE TITLE
NodeJS LTS 8 Compatibility

### ISSUE THREAD

**Issue by NebzHB** [grover/homebridge-dacp#40]
Hello grover,

Could you tell me if it's compatible with the current LTS version of NodeJS. (the package.json ask for node >= 9.3.0)

If not, could it be easily ?

BR's
Nebz

**Comment by julienma** [comment]
Same question.
I'm using https://github.com/oznu/docker-homebridge/, which ships with Node 8.x, and get this error:

```
Plugin /homebridge/node_modules/homebridge-dacp requires Node version of >=9.3.0 which does not satisfy the current Node version of v8.11.1. You may need to upgrade your installation of Node.
```

**Comment by grover** [comment]
I'm trying to stay up to date on the Node side of things. While I do not test with Node LTS, I do not expect any issues with it. Should you have errors other than the message @julienma posted, file bug tickets for those specifically.

Thanks!
