### ISSUE TITLE
Not Supported by Home

### ISSUE THREAD

**Issue by inotna** [grover/homebridge-dacp#5]
I got the plugin up and running and paired. But since it's not possible to control the Apple TV from the Home app directly. Is it possible to get the Play/Pause function to work like a switch in the Home app?

**Comment by grover** [comment]
I'll take a look - that should be doable.

**Comment by grover** [comment]
I just published 0.7.4, which provides a config.json feature to change the play/pause controls to use a regular switch.

**Comment by inotna** [comment]
IT WORKS. Thanks.

pause and plays instant. 

it also works for waking up the Apple TV. So it actually turns on the Apple TV, turns on the soundbar and tv and switches to the right input. Works cool with af Movie scene in Home too.

dims and turn some of the light on and turns on the equipment :D

**Comment by grover** [comment]
Yep that's what I intended it for. Good to know it works for you.
