### ISSUE TITLE
Can't set automation based on media Type

### ISSUE THREAD

**Issue by nitaybz** [grover/homebridge-dacp#6]
Hi @grover !
First of all, thank you so much for this plugin! it's very useful to me as I can set automations based on my apple TV play/paused condition and the media type...

the only problem is that I can't set media type in the conditions since the values range are very big which makes it impossible to choose the numbers 1, 2 or 3 or even any number lower than 100000:
![fullsizeoutput_876](https://user-images.githubusercontent.com/16838394/34342280-86ed52a8-e9b3-11e7-82b3-2edeb4662884.jpeg)

I would suggest to put a max and min limit. I'll open a pull request for that

**Comment by badrabbit** [comment]
Same problem here. Can't set the media type.

**Comment by grover** [comment]
Thanks for the pull request. Where did you come up with the max/min-values? I couldn't find a documentation of the media types to be expected, which is the reason I didn't put in any restrictions.

I'm happy to merge this!

**Comment by nitaybz** [comment]
from HAP-NodeJS: [https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L185](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L185)

thanks for the merge :) and the plugin!

**Comment by grover** [comment]
I meant the values themselves. Because the 64 in docs came from trial&error. I'm not sure if there's anything beyond that. Also I think validValues might be more appropriate as it looks like the values are all powers of two.

**Comment by nitaybz** [comment]
Might be... I did the max to 64 according to your logs.
I just wanted it to be accessible, but if you see another option, go for it :)

**Comment by grover** [comment]
I released 0.7.5 yesteday - i think that closes the issue.
