### ISSUE TITLE
problem installing homebridge-dacp

### ISSUE THREAD

**Issue by JFES** [grover/homebridge-dacp#9]
I am receiving the following error logs after installing homebridge-dacp

an  2 21:12:45 raspberrypi homebridge[668]: [1/2/2018, 9:12:45 PM] ====================
Jan  2 21:12:46 raspberrypi homebridge[668]: [1/2/2018, 9:12:46 PM] ERROR LOADING PLUGIN homebridge-dacp:
Jan  2 21:12:46 raspberrypi homebridge[668]: [1/2/2018, 9:12:46 PM] /usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpClient.js:22
Jan  2 21:12:46 raspberrypi homebridge[668]: async login(options) {
Jan  2 21:12:46 raspberrypi homebridge[668]: ^^^^^
Jan  2 21:12:46 raspberrypi homebridge[668]: SyntaxError: Unexpected identifier
Jan  2 21:12:46 raspberrypi homebridge[668]: at Object.exports.runInThisContext (vm.js:76:16)
Jan  2 21:12:46 raspberrypi homebridge[668]: at Module._compile (module.js:542:28)
Jan  2 21:12:46 raspberrypi homebridge[668]: at Object.Module._extensions..js (module.js:579:10)
Jan  2 21:12:46 raspberrypi homebridge[668]: at Module.load (module.js:487:32)
Jan  2 21:12:46 raspberrypi homebridge[668]: at tryModuleLoad (module.js:446:12)
Jan  2 21:12:46 raspberrypi homebridge[668]: at Function.Module._load (module.js:438:3)
Jan  2 21:12:46 raspberrypi homebridge[668]: at Module.require (module.js:497:17)
Jan  2 21:12:46 raspberrypi homebridge[668]: at require (internal/module.js:20:19)
Jan  2 21:12:46 raspberrypi homebridge[668]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-dacp/src/DacpAccessory.js:6:20)
Jan  2 21:12:46 raspberrypi homebridge[668]: at Module._compile (module.js:570:32)
Jan  2 21:12:46 raspberrypi homebridge[668]: [1/2/2018, 9:12:46 PM] ====================

I uninstalled and reinstalled, verified outdated modules and everything is ok.

Any idea?

**Comment by grover** [comment]
You're likely running on an old node version. What does running

```bash
node -v
```

print for you?

I'd recommend running this with node 9.3.0.

**Comment by estradafernando** [comment]
6.9.1

I update and post result later

**Comment by grover** [comment]
Your node.js installation is too old. Use 8.9.4 or 9.3.0.

**Comment by JFES** [comment]
I upgraded to 9.3.0 and after recompiling it worked. Thanks.
